#ifndef __FILTERUSER_H__
#define __FILTERUSER_H__

//
// Temp file to test filter
//

#define _NDIS_CONTROL_CODE(request,method) \
            CTL_CODE(FILE_DEVICE_PHYSICAL_NETCARD, request, method, FILE_ANY_ACCESS)

#define IOCTL_FILTER_RESTART_ALL             _NDIS_CONTROL_CODE(0, METHOD_BUFFERED)
#define IOCTL_FILTER_RESTART_ONE_INSTANCE    _NDIS_CONTROL_CODE(1, METHOD_BUFFERED)
#define IOCTL_FILTER_ENUMERATE_ALL_INSTANCES _NDIS_CONTROL_CODE(2, METHOD_BUFFERED)
#define IOCTL_FILTER_MODIFY_BLOCK_TABLE      _NDIS_CONTROL_CODE(8, METHOD_BUFFERED)
#define IOCTL_FILTER_GET_ALL_PACKAGES        _NDIS_CONTROL_CODE(9, METHOD_BUFFERED)

#define MAX_FILTER_INSTANCE_NAME_LENGTH     256
#define MAX_FILTER_CONFIG_KEYWORD_LENGTH    256

typedef struct _FILTER_SET_OID
{
    ULONG           InstanceNameLength;
    WCHAR           InstanceName[MAX_FILTER_INSTANCE_NAME_LENGTH];
    NDIS_OID        Oid;
    NDIS_STATUS     Status;
    UCHAR           Data[sizeof(ULONG)];

}FILTER_SET_OID, *PFILTER_SET_OID;

typedef struct _FILTER_BLOCK_TABLE_ENTRY
{
    ULONG           IpAddr;
    USHORT          Port;
	USHORT          BlockType; // 0 - block, 1 - allow
} FILTER_BLOCK_TABLE_ENTRY, *PFILTER_BLOCK_TABLE_ENTRY;

#endif //


